services:
#  app:
#    image: cls
#    container_name: cls
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
##      - redis
##      - rabbitmq
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/logisticsdb
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=password
#      - SPRING_REDIS_HOST=redis
#      - SPRING_REDIS_PORT=6379
#      - SPRING_RABBITMQ_HOST=rabbitmq
#      - SPRING_RABBITMQ_PORT=5672
#    networks:
#      - logistics-network

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: logisticsdb
    ports:
      - "5432:5432"
    networks:
      - logistics-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Redis service for caching
#  redis:
#    image: redis:latest
#    container_name: redis
#    ports:
#      - "6379:6379"
#    networks:
#      - logistics-network

  # RabbitMQ service for messaging
#  rabbitmq:
#    image: rabbitmq:3-management
#    container_name: rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    networks:
#      - logistics-network

networks:
  logistics-network:
    driver: bridge
    name: logistics-network

volumes:
  postgres-data:
