apiVersion: apps/v1
kind: Deployment
metadata:
  name: courier-logistics-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: courier-logistics-system
  template:
    metadata:
      labels:
        app: cls
    spec:
      containers:
        - name: cls
          image: cls:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/logisticsdb"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"
